In [19]:
import pandas as pd
import numpy as np
from IPython.display import clear_output

clear_output()

df_vendas=pd.read_csv("vendas_tech.csv",low_memory=False )
display(df_vendas)
df_gerentes=pd.read_excel("gerentes_lojas.xlsx")
display(df_gerentes)

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,2025-01-01
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,NaN
2,3,2023-02-25,NaN,"Monitor 27""",1200.0,1,Cliente_14859,NaN
3,4,2024-11-19,RIO DE JANEIRO,Mouse Gamer,120.0,2,Cliente_17343,NaN
4,5,2024-01-27,Rio de Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,NaN
...,...,...,...,...,...,...,...,...
100095,94091,2023-10-20,Porto Alegre,iPhone 14,5500.0,1,Cliente_11755,NaN
100096,52883,2024-03-17,Porto Alegre,Notebook Dell,3500.0,2,Cliente_12879,NaN
100097,65070,2023-06-19,Belo Horizonte,Smartphone Samsung,2200.0,2,Cliente_8160,NaN
100098,94031,2024-06-14,Salvador,iPhone 14,5500.0,2,Cliente_28545,NaN
100099,36755,2023-01-03,São Paulo,Notebook HP,3200.0,2,Cliente_3274,NaN

             Loja   Gerente  Meta_Mensal
0       São Paulo    Carlos        50000
1  Rio de Janeiro  Fernanda        60000
2        Curitiba   Roberto        45000
3  Belo Horizonte   Juliana        55000
4          Recife    Marcos        48000
5    Porto Alegre     Pedro        42000
6        Salvador       Ana        52000

In [20]:
 #inspeção
display(df_vendas)
#display(df_vendas.head(15))
#display(df_vendas.tall(15))
display(df_vendas.sample(15))
display(df_vendas.shape)
display(list(df_vendas.columns))
display(df_vendas.info())
display(df_vendas.describe())

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,2025-01-01
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,NaN
2,3,2023-02-25,NaN,"Monitor 27""",1200.0,1,Cliente_14859,NaN
3,4,2024-11-19,RIO DE JANEIRO,Mouse Gamer,120.0,2,Cliente_17343,NaN
4,5,2024-01-27,Rio de Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,NaN
...,...,...,...,...,...,...,...,...
100095,94091,2023-10-20,Porto Alegre,iPhone 14,5500.0,1,Cliente_11755,NaN
100096,52883,2024-03-17,Porto Alegre,Notebook Dell,3500.0,2,Cliente_12879,NaN
100097,65070,2023-06-19,Belo Horizonte,Smartphone Samsung,2200.0,2,Cliente_8160,NaN
100098,94031,2024-06-14,Salvador,iPhone 14,5500.0,2,Cliente_28545,NaN
100099,36755,2023-01-03,São Paulo,Notebook HP,3200.0,2,Cliente_3274,NaN

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
29260,29261,2024-11-09,Curitiba,Cabo HDMI,40.0,2,Cliente_28691,NaN
83771,83772,2023-07-20,RIO DE JANEIRO,Notebook HP,3200.0,2,Cliente_23710,NaN
43567,43568,2024-02-07,Rio de Janeiro,Notebook Dell,3500.0,3,Cliente_14121,NaN
97104,97105,2024-01-20,São Paulo,Smartphone Samsung,2200.0,1,Cliente_23574,NaN
82372,82373,2023-06-10,Rio de Janeiro,Smartphone Samsung,2200.0,1,Cliente_21898,NaN
70076,70077,2023-09-09,São Paulo,Teclado Mecânico,250.0,1,Cliente_29744,NaN
95922,95923,2023-12-21,Porto Alegre,Teclado Mecânico,250.0,3,Cliente_20621,NaN
31458,31459,2023-01-29,Salvador,Cabo HDMI,40.0,1,Cliente_28951,NaN
61186,61187,2024-10-24,RIO DE JANEIRO,Cabo HDMI,40.0,1,Cliente_2186,NaN
83170,83171,2024-05-20,Porto Alegre,Mouse Gamer,120.0,3,Cliente_29932,NaN
59082,59083,2023-04-05,Recife,Teclado Mecânico,250.0,1,Cliente_18544,NaN
62757,62758,2024-08-30,Recife,Notebook Dell,3500.0,1,Cliente_17166,NaN
95061,95062,2024-07-16,Porto Alegre,"Monitor 27""",1200.0,1,Cliente_7042,NaN
84238,84239,2023-05-17,Rio de Janeiro,Smartphone Samsung,2200.0,1,Cliente_9914,NaN
1516,1517,2023-01-22,São Paulo,Mouse Gamer,120.0,1,Cliente_7080,NaN

(100100, 8)

['ID_Pedido',
 'Data',
 'Loja',
 'Produto',
 'Preco_Unitario',
 'Qtd',
 'Cliente',
 'Data_Base']

<class 'pandas.DataFrame'>
RangeIndex: 100100 entries, 0 to 100099
Data columns (total 8 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   ID_Pedido       100100 non-null  int64
 1   Data            100100 non-null  str
 2   Loja            98099 non-null   str
 3   Produto         100100 non-null  str
 4   Preco_Unitario  100100 non-null  float64
 5   Qtd             100100 non-null  int64
 6   Cliente         100100 non-null  str
 7   Data_Base       1 non-null       str
dtypes: float64(1), int64(2), str(5)
memory usage: 6.1 MB

None

           ID_Pedido  Preco_Unitario            Qtd
count  100100.000000   100100.000000  100100.000000
mean    50004.810180     2000.204595       1.499101
std     28866.872543     1841.050733       1.241605
min         1.000000       40.000000       1.000000
25%     25008.750000      120.000000       1.000000
50%     50004.500000     1200.000000       1.000000
75%     75002.250000     3200.000000       1.000000
max    100000.000000     5500.000000      10.000000

In [26]:
#tratamento de dados
#colunas
display(df_vendas["Loja"])
display(df_vendas[["Loja", "Cliente"]])

df_analise=df_vendas.drop(columns=["Data_Base"])



#nulos
#df_analise=df_analise.dropna() #excluir todas as linhas que tem 1 valor vazio
df_analise["Loja"] = df_analise["Loja"].fillna("online")#preencher valores vazios



#tipos de dados

#duplicatas


display(df_analise)

0              São Paulo
1         Belo Horizonte
2                    NaN
3         RIO DE JANEIRO
4         Rio de Janeiro
               ...
100095      Porto Alegre
100096      Porto Alegre
100097    Belo Horizonte
100098          Salvador
100099        São Paulo
Name: Loja, Length: 100100, dtype: str

                  Loja        Cliente
0            São Paulo   Cliente_4095
1       Belo Horizonte   Cliente_8750
2                  NaN  Cliente_14859
3       RIO DE JANEIRO  Cliente_17343
4       Rio de Janeiro  Cliente_23377
...                ...            ...
100095    Porto Alegre  Cliente_11755
100096    Porto Alegre  Cliente_12879
100097  Belo Horizonte   Cliente_8160
100098        Salvador  Cliente_28545
100099      São Paulo    Cliente_3274

[100100 rows x 2 columns]

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750
2,3,2023-02-25,online,"Monitor 27""",1200.0,1,Cliente_14859
3,4,2024-11-19,RIO DE JANEIRO,Mouse Gamer,120.0,2,Cliente_17343
4,5,2024-01-27,Rio de Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377
...,...,...,...,...,...,...,...
100095,94091,2023-10-20,Porto Alegre,iPhone 14,5500.0,1,Cliente_11755
100096,52883,2024-03-17,Porto Alegre,Notebook Dell,3500.0,2,Cliente_12879
100097,65070,2023-06-19,Belo Horizonte,Smartphone Samsung,2200.0,2,Cliente_8160
100098,94031,2024-06-14,Salvador,iPhone 14,5500.0,2,Cliente_28545
100099,36755,2023-01-03,São Paulo,Notebook HP,3200.0,2,Cliente_3274